javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\adaptors\guitarPro\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\adaptors\midi\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\adaptors\song\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\adaptors\song\event\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\adaptors\song\impl\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\guitarPro\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\guitarPro\statistics\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\guitarPro\version1\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\guitarPro\version2\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\guitarPro\version3\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\guitarPro\version4\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\codecs\midi\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\gui\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\gui\listeners\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\gui\midi\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\gui\unused\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\players\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\players\gui\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\players\sound\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\players\sound\midi\*.java
javac -deprecation -g -d ..\bin -classpath .;..\dist\Common.jar dguitar\players\sound\midi\demo\*.java
