/*
 * ColorPanel.java
 *
 * Created on 3 de marzo de 2005, 05:39 AM
 */

package dguitar.gui;

import i18n.Internationalized;

/**
 * This class it here the different ColorPanel*s are added with a JTabbedPane
 *  
 * At this moment it adds a 
 * @author  Mauricio Gracia Gutiérrez
 */
public class ColorPanel extends javax.swing.JPanel 
implements Internationalized {
    /**
	 * 
	 */
	private static final long serialVersionUID = 4217077360630048204L;
	protected ColorPanelSelect fretColors ;
    protected ColorPanelSelect rhythmColors ;

    /** Creates new form ColorPanel 
     * that allow the user to select the different DisplayOptions 
     */
    public ColorPanel() {
        initComponents();
        this.fretColors = new ColorPanelSelect() ;
        this.rhythmColors = new ColorPanelSelect() ;
        //INTERNATIONALIZATION 
        setLangText();
    }
    public void setLangText() {
    	this.tabs.add(DGuitar.lang.getString("colorFrets_Notes"), fretColors) ;
    	this.tabs.add(DGuitar.lang.getString("colorRhythm_Lines"), rhythmColors) ;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tabs = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        add(tabs, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
    
}
