/*
 * DGPlayer.java
 *
 * Created on 14 de marzo de 2005, 1:15
 */

package dguitar.gui.unused;

/**
 * This class will allow the user to select a list of files and play them.
 *
 * @author  Mauricio Gracia Gutiérrez
 */
public class DGPlayer extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1620050906861776608L;

	/** Creates new form DGPlayer */
    public DGPlayer() {
        initComponents();
        postInit() ;
    }
    
    private void postInit() {
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DGPlayer().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
